# Scaffolding generated by Casein v.3.1.11

module Casein
  class ArticlesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Articles'
  		@articles = Article.paginate(:page => params[:page], :per_page=> APP_CONFIG['Pagination']['per_page'], :order => 'created_at ASC')     
      respond_to do |format|
        format.js
      end      
    end
  
    def show
      @casein_page_title = 'View article'
      @article = Article.find params[:id]
    end
 
    def new
      @casein_page_title = 'Add a new article'
    	@article = Article.new
    end

    def create
      @article = Article.new params[:article]
    
      if @article.save
        flash[:notice] = 'Article created'
        redirect_to casein_articles_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new article'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update article'
      
      @article = Article.find params[:id]
    
      if @article.update_attributes params[:article]
        #~ flash[:notice] = 'Article has been updated'
        @casein_page_title = 'Articles'
        @articles = Article.paginate(:page => params[:page], :per_page=> APP_CONFIG['Pagination']['per_page'], :order => 'created_at ASC')        
        render :action=> :index
      else
        flash.now[:warning] = 'There were problems when trying to update this article'
        render :action => :show
      end
    end
 
    def destroy
      @article = Article.find params[:id]

      @article.destroy
      #~ flash[:notice] = 'Article has been deleted'
      #~ redirect_to casein_articles_path
      @casein_page_title = 'Articles'
      @articles = Article.paginate :page => params[:page] 
      render :action=> :index
    end
  
  end
end